os:
  - osx

language: node_js
node_js:
  - "12"

before_install:
  - nvm install 0.12
  - brew update

install:
  - npm install
  - gauge install js
  - gauge install html-report

script:
  - gauge run specs
