os:
  - linux

language: node_js
node_js:
  - "node"
env:
  - GAUGE_TELEMETRY_ENABLED=false GAUGE_PREFIX=/tmp
before_install:
  - npm install
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - curl -sSfL https://github.com/getgauge/gauge-tests/raw/master/install_latest_gauge_nightly.sh | bash
  - export PATH=$PATH:$GAUGE_PREFIX/bin

install:
  - sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
  - echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install gauge  
  - ./install_js.sh

script:
  - gauge run specs
