os:
  - osx

language: node_js
node_js:
  - "node"

before_install:
  - brew update

install:
  - npm install
  - brew install gauge
  - gauge install js
  - gauge install html-report

script:
  - gauge run specs
