environment:
  nodejs_version: "6"

version: 1.0.{build}
init:
- ps: .\installGaugeNightly.sh
- ps: Install-Product node $env:nodejs_version
- ps: sleep 10
- ps: npm install npm@latest -g
- ps: node --version
- ps: npm --version
install:
- ps: >-
    $gauge=$env:ProgramFiles + "\gauge\bin\gauge.exe"

    &$gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/

    &$gauge install
cache:
- packages
- '%APPDATA%\gauge\plugins'
build: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/68b514dcb2c08a6a5809
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
test_script:
- ps: >-
    $gauge=$env:ProgramFiles + "\gauge\bin\gauge.exe"

    &$gauge version

    &$gauge run specs --tags=!windows
artifacts:
- path: ./reports/html-reportreport
  name: gauge-reports
- path: ./failure_reports/html-report
  name: gauge-reports-failure
on_finish:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\reports\xml-report\result.xml))
