environment:
  nodejs_version: "6"

version: 1.0.{build}
init:
- ps: choco install gauge
install:
  - ps: .\install_js.sh
  - ps: sleep 30
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: sleep 30
  - ps: npm install
cache:
- packages
- '%APPDATA%\gauge\plugins'
build: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/68b514dcb2c08a6a5809
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
test_script:
  - ps: node --version
  - ps: npm --version
  # run tests
  - ps: gauge version
  - ps: gauge run specs
artifacts:
- path: ./reports/html-reportreport
  name: gauge-reports
- path: ./failure_reports/html-report
  name: gauge-reports-failure
on_finish:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\reports\xml-report\result.xml))
